### ISSUE TITLE
automation passcode for Bosch2000/3000

### ISSUE THREAD

**Issue by sateeshruttala** [EHylands/homebridge-boschcontrolpanel_bgseries#13]
from where do we  get the automation passcode for Bosch2000/3000 series panel

**Comment by EHylands** [comment]
Need to update documentation. On Solution panels, you can use your normal RSC pass code.

**Comment by sateeshruttala** [comment]
you mean the the passcode we enter on the keypad to alarm

**Comment by sateeshruttala** [comment]
I get this error while i use the passcode for enabling and disabling the alarm 
[05/02/2023, 10:32:53 am] [homebridge-boschcontrolpanel_bgseries] Aborting: Point undefined in config file is not configured on the panel
[05/02/2023, 10:32:53 am] [homebridge-boschcontrolpanel_bgseries] Aborting plugin operation - Failed Config Phase 2

**Comment by EHylands** [comment]
> I get this error while i use the passcode for enabling and disabling the alarm [05/02/2023, 10:32:53 am] [homebridge-boschcontrolpanel_bgseries] Aborting: Point undefined in config file is not configured on the panel [05/02/2023, 10:32:53 am] [homebridge-boschcontrolpanel_bgseries] Aborting plugin operation - Failed Config Phase 2

This issue is fixed in an upcoming version.
In Homebridge plugin config page, you can install plugin alternate beta version 0.6.18 for the fix.
<img width="853" alt="Screenshot 2023-02-04 at 6 44 15 PM" src="https://user-images.githubusercontent.com/90003064/216794226-d8c393f1-aac8-4d1b-b7a3-70f44696c6c2.png">

**Comment by sateeshruttala** [comment]
I still get the same error
![image](https://user-images.githubusercontent.com/70090158/216794313-5da29e5b-a999-4603-9806-09e0952e3927.png)
![image](https://user-images.githubusercontent.com/70090158/216794321-f35a2471-47e0-4fe9-8401-5c860fe2849f.png)
![image](https://user-images.githubusercontent.com/70090158/216794368-2becfca2-6634-4f17-a392-76ff4757b348.png)
![image](https://user-images.githubusercontent.com/70090158/216794386-79a3b122-c764-47a3-acbe-cd0b38d464b7.png)

**Comment by EHylands** [comment]
Do you have a point without a valid PointNumber in your config file ?
`"Points": [{
    "PointNumber": 1,
    "SensorType": "ContactSensor",
    "Active": true
}]`

**Comment by sateeshruttala** [comment]
The config file looks below ,rightnow I get this error 
[05/02/2023, 11:02:07 am] [homebridge-boschcontrolpanel_bgseries] Aborting: Output3 in config file is not configured on the panel
[05/02/2023, 11:02:07 am] [homebridge-boschcontrolpanel_bgseries] Aborting plugin operation - Failed Config Phase 2

it is standard config the Bosch 3000 series config 

{
    "Host": "192.168.20.52",
    "Port": 7700,
    "Passcode": "0304",
    "ForceLegacyMode": true,
    "MasterFireAlarm": false,
    "MasterPersonnalAlarm": false,
    "MasterGazAlarm": false,
    "MasterBurglaryAlarm": false,
    "LogConfidenceMessage": false,
    "LogPoint": false,
    "LogOutput": true,
    "LogAreaAlarm": true,
    "LogAreaArmingStatus": true,
    "Areas": [
        {
            "AreaNumber": 1,
            "PasscodeFollowsScope": false,
            "Active": true
        }
    ],
    "Outputs": [
        {
            "OutputNumber": 3,
            "Active": true
        }
    ],
    "Points": [
        {
            "PointNumber": 1,
            "SensorType": "contactSensor",
            "Active": true
        },
        {
            "PointNumber": 2,
            "SensorType": "contactSensor",
            "Active": true
        },
        {
            "PointNumber": 3,
            "SensorType": "contactSensor",
            "Active": true
        }
    ],
    "_bridge": {
        "username": "0E:1A:BC:91:95:B4",
        "port": 37258
    },
    "platform": "BoschControlPanel_BGSeries"
}

**Comment by EHylands** [comment]
I think it was reported by other user that Solution 3000 onboard outputs are not accessible from automation protocol.
I unfortunatly down own a Solution panel myself

**Comment by sateeshruttala** [comment]
it worked thank you for the support

**Comment by EHylands** [comment]
Great ! 
You are the first one to test beta version 0.6.18
Would you mind disabling 'Legacy Mode' in your config file and providing your log file with Homebridge running in debug mode (-D) ?

For the moment, Solution 3000 panel can only run with data pooling, but an upcoming firmware release will enable pushed notifications !

**Comment by sateeshruttala** [comment]
Sure i will do that and send the log

**Comment by EHylands** [comment]
Was `Web and Automation Security` enable by default on your panel or you had to enable it through A-Link ?
